config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :articles do
  	resources :comments
  end

  get '/users-listing', to: 'users#index'
  root 'articles#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	belongs_to :user
	validates :title, presence: true, length: { minimum: 4 }
	validates :content, presence: true, length: { minimum: 30}
	# Needed for carrierwave
	mount_uploader :image, ImageUploader
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :article
	belongs_to :user
	validates :body, presence: true, length: { minimum: 2}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :articles, dependent: :destroy
	has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :find_article,except: [:index,:new,:create]
	before_action :authenticate_user!,except: [:index,:show]
	def index
		@articles = Article.all.order("created_at DESC")
	end

	def new
		@article = current_user.articles.build
	end

	def create
		@article = current_user.articles.build(article_params)
		if @article.save
			flash[:success] = "Article successfully created !"
			redirect_to article_path(@article)
		else
			flash[:danger] = "Article failed to create !"
			render 'new'
		end
	end

	def show
	end

	def edit
	end

	def update
		if @article.update(article_params)
			flash[:success] = "Article successfully updated !"
			redirect_to article_path(@article)
		else
			flash[:danger] = "Article failed to update !"
			render 'edit'
		end
	end

	def destroy
		@article.delete
		redirect_to root_path
		flash[:danger] = "Article successfully deleted !"
	end

	private

	def article_params
		params.require(:article).permit(:title,:content,:image,:remove_image)
	end

	def find_article
		@article = Article.find(params[:id])
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_comment,except: [:create]
	before_action :authenticate_user!
	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
		if @comment.save
			flash[:success] = "Comment successfully created !"
			redirect_to article_path(@article)
		else
			flash[:danger] = "Comment failed to create !"
			render '_form'
		end
	end

	def edit
	end

	def update
		if @comment.update(comment_params)
			flash[:success] = "Comment successfully updated !"
			redirect_to article_path(@article)
		else
			flash[:danger] = "Comment failed to update !"
			render 'edit'
		end
	end

	def destroy
		@comment.delete
		redirect_to article_path(@article)
		flash[:danger] = "Comment successfully deleted !"
	end

	private

	def find_comment
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
	end

	def comment_params
		params.require(:comment).permit(:body)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all.order("created_at DESC")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.haml
= simple_form_for @article do |f|
	- if @article.errors.any?
		- @article.errors.full_messages.each do |msg|
			%ul
				%li= msg
	%p= f.input :title
	%p= f.input :image, as: :file
	- if f.object.image?
		= image_tag f.object.image.medium.url
		= f.check_box :remove_image
	%p= f.input :content, input_html: { rows: 10}
	%p= f.button :"submit", class:'btn btn-default'

= link_to "Cancel", @article

app/views/articles/edit.html.haml
.col-md-6.col-md-offset-3.well
	%h1.text-center Edit article
	= render 'form'

app/views/articles/index.html.haml
- @articles.each do |article|	
	%h1.jumbotron.text-center#index-radius
		= link_to article do
			%p
				= image_tag article.image.thumb.url
			= article.title
		%p
			Submited by
			= article.user.email

app/views/articles/new.html.haml
.col-md-6.col-md-offset-3.well
	%h1.text-center New Article
	= render 'form'

app/views/articles/show.html.haml
.row
	.well.col-md-8.col-md-offset-2.text-center
		%h1= @article.title
		%p= image_tag @article.image.medium.url
		%p= @article.content
		%p
			submited by
			= @article.user.email
		-if user_signed_in?
			%p
				= link_to "Edit", edit_article_path, class:'btn btn-success'
				= link_to "Delete", @article, method: :delete, data: { confirm: "Are you sure?"}, class:'btn btn-danger'

%br/
%br/
%br/

.row.col-md-6.col-md-offset-3.text-center.well
	- if @article.comments.count == 0
		%h3 There are no comments at the moment
	- else
		%h3= pluralize(@article.comments.count, 'comment')
		%h3= render @article.comments.order("created_at DESC")

%br/
%br/
%br/
- if user_signed_in?
	= render 'comments/form'

app/views/comments/_comment.html.haml
%h3= comment.body
- if user_signed_in?
	= link_to "Edit comment", edit_article_comment_path(comment.article,comment), class:'btn btn-success'
	= link_to "Delete comment", [comment.article,comment], method: :delete, data: { confirm: "Are you sure?"}, class:'btn btn-danger'
%br/

app/views/comments/_form.html.haml
.row.col-md-6.col-md-offset-3.well
	%h2.text-center New comment
	= simple_form_for([@article,@article.comments.build]) do |f|
		%p= f.input :body, input_html: { rows: 6}
		%p= f.submit

app/views/comments/edit.html.haml
.row.col-md-6.col-md-offset-3.well
	%h2.text-center Edit comment
	= simple_form_for([@article,@comment]) do |f|
		%p= f.input :body, input_html: { rows: 10}
		%p= f.submit

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title HameldBlog
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
	= javascript_include_tag 'application', 'data-turbolinks-track' => true 
	= csrf_meta_tags
%body
	- flash.each do |name,msg|
		= content_tag :div, msg, class: "alert alert-#{name}"

	%nav.navbar.navbar-inverse.navbar-fixed-top
		.container
			.navbar-header
				%button.navbar-toggle
				= link_to "HameldBlog", root_path,class:'navbar-brand'
			.collapse.navbar-collapse#myNavbar
				%ul.nav.navbar-nav
					%li= link_to "New Article", new_article_path
				%ul.nav.navbar-nav.navbar-right
					- if user_signed_in?
						%li
							= link_to "Account", edit_user_registration_path 
						%li
							= link_to destroy_user_session_path, method: :delete do
								%span.glyphicon.glyphicon-log-in
								Log Out
					- else
						%li
							= link_to new_user_registration_path do
								Sign Up
						%li
							= link_to new_user_session_path do
								Sign In
	.container
		= yield

app/views/users/index.html.haml
- @users.each do |user|
	.col-md-4.col-md-offset-4.well
		%h3.text-center= user.email